name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: write  # Allows the workflow to push changes to the repository

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      # Opsional commit changes jika ada generate report atau log
      - name: Commit changes
        if: always()
        run: |
          git config --local user.name "fadlian17"
          git config --local user.email "alfansyahfadlian@gmail.com"
          git add .
          git commit -m "Auto-commit test artifacts" || echo "Nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"